<?php require APPROOT . '/views/inc/header.phtml' ;?>
<?php require APPROOT . '/views/inc/navbar.phtml';?>
    <div class="row">
        <div class="col-sm-8 col-md-6 col-lg-5 col-xl-4 mx-auto">
            <div class="card mt-5">
                <div class="card-header text-center">
                    <h4 class="h4">Creat New Account</h4>
                </div>
                <div class="card-body bg-light">
                    <div class="my-4">You need to fill all fields to register.</div>

                    <form action="<?php echo URLROOT . '/users/register'?>" method="post">
                        <div class="form-group">
                            <label for="name">Name: <sup>*</sup></label>
                            <input type="text" name="name" class="form-control form-control-lg<?php echo
                            (!empty($data['error_name'])) ? 'is_invalid' : ''; ?>" value="<?php echo $data['name'] ;?>">
                            <span class="invalid-feedback"><?php echo $data['error_name']; ?></span>
                        </div>

                        <div class="form-group">
                            <label for="email">Email: <sup>*</sup></label>
                            <input type="email" name="email" class="form-control form-control-lg
                                <?php echo (!empty($data['error_email'])) ? 'is_invalid' : ''; ?>"
                                   value="<?php echo $data['email'] ;?>">
                            <span class="invalid-feedback"><?php echo $data['error_email']; ?></span>
                        </div>

                        <div class="form-group">
                            <label for="password">Password: <sup>*</sup></label>
                            <input type="password" name="password" class="form-control form-control-lg
                                <?php echo (!empty($data['error_password'])) ? 'is_invalid' : ''; ?>"
                                   value="<?php echo $data['password'] ;?>">
                            <span class="invalid-feedback"><?php echo $data['error_password']; ?></span>
                        </div>

                        <div class="form-group">
                            <label for="confirm_password">Confirm Password: <sup>*</sup></label>
                            <input type="password" name="confirm_password" class="form-control form-control-lg
                                <?php echo (!empty($data['error_confirm_password'])) ? 'is_invalid' : ''; ?>"
                                   value="<?php echo $data['confirm_password'] ;?>">
                            <span class="invalid-feedback"><?php echo $data['error_confirm_password']; ?></span>
                        </div>
                </div>
                        <div class="card-footer">
                            <div class="row  align-items-center">
                                <div class="col">
                                    <input type="submit" value="Register" class="btn btn-success btn-block">
                                </div>
                                <div class="col text-center">
                                    <a href="<?php echo URLROOT . '/users/login' ;?>" class="btn btn-light  btn-block">Have an account? Login</a>
                                </div>
                            </div>
                        </div>

                    </form>
            </div>
        </div>
    </div>
<?php require APPROOT . '/views/inc/footer.phtml';?>