    <script type="text/javascript" src="<?php echo URLROOT . '/assets/jquery/jquery-3.3.1.min.js' ;?>"></script>
    <script type="text/javascript" src="<?php echo URLROOT . '/assets/bootstrap-4.1.3-dist/js/bootstrap.bundle.js' ;?>"></script>
    <script type="text/javascript" src="<?php echo URLROOT . '/js/main.js' ;?>"></script>
    <script type="text/javascript">
        $(function() {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</body>
</html>