<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="<?php echo URLROOT . '/assets/bootstrap-4.1.3-dist/css/bootstrap.css' ?>"/>
    <link rel="stylesheet" href="<?php echo URLROOT . '/css/style.css' ;?>"/>
    <link rel="icon" href="http://localhost/favicon.ico?"/>
    <title><?php echo $data['title'];?></title>
</head>
<body>

